//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.hyCodeServiceSoap")]
    public interface hyCodeServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 request 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createVmcardQRcode", ReplyAction="*")]
        test.ServiceReference1.createVmcardQRcodeResponse createVmcardQRcode(test.ServiceReference1.createVmcardQRcodeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 request 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modifyVmcardInfo", ReplyAction="*")]
        test.ServiceReference1.modifyVmcardInfoResponse modifyVmcardInfo(test.ServiceReference1.modifyVmcardInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 request 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPersonInfo", ReplyAction="*")]
        test.ServiceReference1.getPersonInfoResponse getPersonInfo(test.ServiceReference1.getPersonInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 request 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getActiveQrCode", ReplyAction="*")]
        test.ServiceReference1.getActiveQrCodeResponse getActiveQrCode(test.ServiceReference1.getActiveQrCodeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 request 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPersonInfoByQrCode", ReplyAction="*")]
        test.ServiceReference1.getPersonInfoByQrCodeResponse getPersonInfoByQrCode(test.ServiceReference1.getPersonInfoByQrCodeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 request 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/queryIfHasRegistered", ReplyAction="*")]
        test.ServiceReference1.queryIfHasRegisteredResponse queryIfHasRegistered(test.ServiceReference1.queryIfHasRegisteredRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 request 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/activateVmcardQRcode", ReplyAction="*")]
        test.ServiceReference1.activateVmcardQRcodeResponse activateVmcardQRcode(test.ServiceReference1.activateVmcardQRcodeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 request 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Encrypt", ReplyAction="*")]
        test.ServiceReference1.EncryptResponse Encrypt(test.ServiceReference1.EncryptRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 request 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeEncrypt", ReplyAction="*")]
        test.ServiceReference1.DeEncryptResponse DeEncrypt(test.ServiceReference1.DeEncryptRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createVmcardQRcodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createVmcardQRcode", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.createVmcardQRcodeRequestBody Body;
        
        public createVmcardQRcodeRequest() {
        }
        
        public createVmcardQRcodeRequest(test.ServiceReference1.createVmcardQRcodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createVmcardQRcodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public createVmcardQRcodeRequestBody() {
        }
        
        public createVmcardQRcodeRequestBody(string request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createVmcardQRcodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createVmcardQRcodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.createVmcardQRcodeResponseBody Body;
        
        public createVmcardQRcodeResponse() {
        }
        
        public createVmcardQRcodeResponse(test.ServiceReference1.createVmcardQRcodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createVmcardQRcodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string createVmcardQRcodeResult;
        
        public createVmcardQRcodeResponseBody() {
        }
        
        public createVmcardQRcodeResponseBody(string createVmcardQRcodeResult) {
            this.createVmcardQRcodeResult = createVmcardQRcodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modifyVmcardInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modifyVmcardInfo", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.modifyVmcardInfoRequestBody Body;
        
        public modifyVmcardInfoRequest() {
        }
        
        public modifyVmcardInfoRequest(test.ServiceReference1.modifyVmcardInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modifyVmcardInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public modifyVmcardInfoRequestBody() {
        }
        
        public modifyVmcardInfoRequestBody(string request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modifyVmcardInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modifyVmcardInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.modifyVmcardInfoResponseBody Body;
        
        public modifyVmcardInfoResponse() {
        }
        
        public modifyVmcardInfoResponse(test.ServiceReference1.modifyVmcardInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modifyVmcardInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string modifyVmcardInfoResult;
        
        public modifyVmcardInfoResponseBody() {
        }
        
        public modifyVmcardInfoResponseBody(string modifyVmcardInfoResult) {
            this.modifyVmcardInfoResult = modifyVmcardInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPersonInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPersonInfo", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.getPersonInfoRequestBody Body;
        
        public getPersonInfoRequest() {
        }
        
        public getPersonInfoRequest(test.ServiceReference1.getPersonInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPersonInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public getPersonInfoRequestBody() {
        }
        
        public getPersonInfoRequestBody(string request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPersonInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPersonInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.getPersonInfoResponseBody Body;
        
        public getPersonInfoResponse() {
        }
        
        public getPersonInfoResponse(test.ServiceReference1.getPersonInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPersonInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPersonInfoResult;
        
        public getPersonInfoResponseBody() {
        }
        
        public getPersonInfoResponseBody(string getPersonInfoResult) {
            this.getPersonInfoResult = getPersonInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getActiveQrCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getActiveQrCode", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.getActiveQrCodeRequestBody Body;
        
        public getActiveQrCodeRequest() {
        }
        
        public getActiveQrCodeRequest(test.ServiceReference1.getActiveQrCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getActiveQrCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public getActiveQrCodeRequestBody() {
        }
        
        public getActiveQrCodeRequestBody(string request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getActiveQrCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getActiveQrCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.getActiveQrCodeResponseBody Body;
        
        public getActiveQrCodeResponse() {
        }
        
        public getActiveQrCodeResponse(test.ServiceReference1.getActiveQrCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getActiveQrCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getActiveQrCodeResult;
        
        public getActiveQrCodeResponseBody() {
        }
        
        public getActiveQrCodeResponseBody(string getActiveQrCodeResult) {
            this.getActiveQrCodeResult = getActiveQrCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPersonInfoByQrCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPersonInfoByQrCode", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.getPersonInfoByQrCodeRequestBody Body;
        
        public getPersonInfoByQrCodeRequest() {
        }
        
        public getPersonInfoByQrCodeRequest(test.ServiceReference1.getPersonInfoByQrCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPersonInfoByQrCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public getPersonInfoByQrCodeRequestBody() {
        }
        
        public getPersonInfoByQrCodeRequestBody(string request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPersonInfoByQrCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPersonInfoByQrCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.getPersonInfoByQrCodeResponseBody Body;
        
        public getPersonInfoByQrCodeResponse() {
        }
        
        public getPersonInfoByQrCodeResponse(test.ServiceReference1.getPersonInfoByQrCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPersonInfoByQrCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPersonInfoByQrCodeResult;
        
        public getPersonInfoByQrCodeResponseBody() {
        }
        
        public getPersonInfoByQrCodeResponseBody(string getPersonInfoByQrCodeResult) {
            this.getPersonInfoByQrCodeResult = getPersonInfoByQrCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryIfHasRegisteredRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queryIfHasRegistered", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.queryIfHasRegisteredRequestBody Body;
        
        public queryIfHasRegisteredRequest() {
        }
        
        public queryIfHasRegisteredRequest(test.ServiceReference1.queryIfHasRegisteredRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class queryIfHasRegisteredRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public queryIfHasRegisteredRequestBody() {
        }
        
        public queryIfHasRegisteredRequestBody(string request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryIfHasRegisteredResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queryIfHasRegisteredResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.queryIfHasRegisteredResponseBody Body;
        
        public queryIfHasRegisteredResponse() {
        }
        
        public queryIfHasRegisteredResponse(test.ServiceReference1.queryIfHasRegisteredResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class queryIfHasRegisteredResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string queryIfHasRegisteredResult;
        
        public queryIfHasRegisteredResponseBody() {
        }
        
        public queryIfHasRegisteredResponseBody(string queryIfHasRegisteredResult) {
            this.queryIfHasRegisteredResult = queryIfHasRegisteredResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class activateVmcardQRcodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="activateVmcardQRcode", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.activateVmcardQRcodeRequestBody Body;
        
        public activateVmcardQRcodeRequest() {
        }
        
        public activateVmcardQRcodeRequest(test.ServiceReference1.activateVmcardQRcodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class activateVmcardQRcodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public activateVmcardQRcodeRequestBody() {
        }
        
        public activateVmcardQRcodeRequestBody(string request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class activateVmcardQRcodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="activateVmcardQRcodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.activateVmcardQRcodeResponseBody Body;
        
        public activateVmcardQRcodeResponse() {
        }
        
        public activateVmcardQRcodeResponse(test.ServiceReference1.activateVmcardQRcodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class activateVmcardQRcodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string activateVmcardQRcodeResult;
        
        public activateVmcardQRcodeResponseBody() {
        }
        
        public activateVmcardQRcodeResponseBody(string activateVmcardQRcodeResult) {
            this.activateVmcardQRcodeResult = activateVmcardQRcodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Encrypt", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.EncryptRequestBody Body;
        
        public EncryptRequest() {
        }
        
        public EncryptRequest(test.ServiceReference1.EncryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public EncryptRequestBody() {
        }
        
        public EncryptRequestBody(string request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EncryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.EncryptResponseBody Body;
        
        public EncryptResponse() {
        }
        
        public EncryptResponse(test.ServiceReference1.EncryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncryptResult;
        
        public EncryptResponseBody() {
        }
        
        public EncryptResponseBody(string EncryptResult) {
            this.EncryptResult = EncryptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeEncryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeEncrypt", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.DeEncryptRequestBody Body;
        
        public DeEncryptRequest() {
        }
        
        public DeEncryptRequest(test.ServiceReference1.DeEncryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeEncryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        public DeEncryptRequestBody() {
        }
        
        public DeEncryptRequestBody(string request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeEncryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeEncryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.ServiceReference1.DeEncryptResponseBody Body;
        
        public DeEncryptResponse() {
        }
        
        public DeEncryptResponse(test.ServiceReference1.DeEncryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeEncryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeEncryptResult;
        
        public DeEncryptResponseBody() {
        }
        
        public DeEncryptResponseBody(string DeEncryptResult) {
            this.DeEncryptResult = DeEncryptResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface hyCodeServiceSoapChannel : test.ServiceReference1.hyCodeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class hyCodeServiceSoapClient : System.ServiceModel.ClientBase<test.ServiceReference1.hyCodeServiceSoap>, test.ServiceReference1.hyCodeServiceSoap {
        
        public hyCodeServiceSoapClient() {
        }
        
        public hyCodeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public hyCodeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public hyCodeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public hyCodeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.ServiceReference1.createVmcardQRcodeResponse test.ServiceReference1.hyCodeServiceSoap.createVmcardQRcode(test.ServiceReference1.createVmcardQRcodeRequest request) {
            return base.Channel.createVmcardQRcode(request);
        }
        
        public string createVmcardQRcode(string request) {
            test.ServiceReference1.createVmcardQRcodeRequest inValue = new test.ServiceReference1.createVmcardQRcodeRequest();
            inValue.Body = new test.ServiceReference1.createVmcardQRcodeRequestBody();
            inValue.Body.request = request;
            test.ServiceReference1.createVmcardQRcodeResponse retVal = ((test.ServiceReference1.hyCodeServiceSoap)(this)).createVmcardQRcode(inValue);
            return retVal.Body.createVmcardQRcodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.ServiceReference1.modifyVmcardInfoResponse test.ServiceReference1.hyCodeServiceSoap.modifyVmcardInfo(test.ServiceReference1.modifyVmcardInfoRequest request) {
            return base.Channel.modifyVmcardInfo(request);
        }
        
        public string modifyVmcardInfo(string request) {
            test.ServiceReference1.modifyVmcardInfoRequest inValue = new test.ServiceReference1.modifyVmcardInfoRequest();
            inValue.Body = new test.ServiceReference1.modifyVmcardInfoRequestBody();
            inValue.Body.request = request;
            test.ServiceReference1.modifyVmcardInfoResponse retVal = ((test.ServiceReference1.hyCodeServiceSoap)(this)).modifyVmcardInfo(inValue);
            return retVal.Body.modifyVmcardInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.ServiceReference1.getPersonInfoResponse test.ServiceReference1.hyCodeServiceSoap.getPersonInfo(test.ServiceReference1.getPersonInfoRequest request) {
            return base.Channel.getPersonInfo(request);
        }
        
        public string getPersonInfo(string request) {
            test.ServiceReference1.getPersonInfoRequest inValue = new test.ServiceReference1.getPersonInfoRequest();
            inValue.Body = new test.ServiceReference1.getPersonInfoRequestBody();
            inValue.Body.request = request;
            test.ServiceReference1.getPersonInfoResponse retVal = ((test.ServiceReference1.hyCodeServiceSoap)(this)).getPersonInfo(inValue);
            return retVal.Body.getPersonInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.ServiceReference1.getActiveQrCodeResponse test.ServiceReference1.hyCodeServiceSoap.getActiveQrCode(test.ServiceReference1.getActiveQrCodeRequest request) {
            return base.Channel.getActiveQrCode(request);
        }
        
        public string getActiveQrCode(string request) {
            test.ServiceReference1.getActiveQrCodeRequest inValue = new test.ServiceReference1.getActiveQrCodeRequest();
            inValue.Body = new test.ServiceReference1.getActiveQrCodeRequestBody();
            inValue.Body.request = request;
            test.ServiceReference1.getActiveQrCodeResponse retVal = ((test.ServiceReference1.hyCodeServiceSoap)(this)).getActiveQrCode(inValue);
            return retVal.Body.getActiveQrCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.ServiceReference1.getPersonInfoByQrCodeResponse test.ServiceReference1.hyCodeServiceSoap.getPersonInfoByQrCode(test.ServiceReference1.getPersonInfoByQrCodeRequest request) {
            return base.Channel.getPersonInfoByQrCode(request);
        }
        
        public string getPersonInfoByQrCode(string request) {
            test.ServiceReference1.getPersonInfoByQrCodeRequest inValue = new test.ServiceReference1.getPersonInfoByQrCodeRequest();
            inValue.Body = new test.ServiceReference1.getPersonInfoByQrCodeRequestBody();
            inValue.Body.request = request;
            test.ServiceReference1.getPersonInfoByQrCodeResponse retVal = ((test.ServiceReference1.hyCodeServiceSoap)(this)).getPersonInfoByQrCode(inValue);
            return retVal.Body.getPersonInfoByQrCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.ServiceReference1.queryIfHasRegisteredResponse test.ServiceReference1.hyCodeServiceSoap.queryIfHasRegistered(test.ServiceReference1.queryIfHasRegisteredRequest request) {
            return base.Channel.queryIfHasRegistered(request);
        }
        
        public string queryIfHasRegistered(string request) {
            test.ServiceReference1.queryIfHasRegisteredRequest inValue = new test.ServiceReference1.queryIfHasRegisteredRequest();
            inValue.Body = new test.ServiceReference1.queryIfHasRegisteredRequestBody();
            inValue.Body.request = request;
            test.ServiceReference1.queryIfHasRegisteredResponse retVal = ((test.ServiceReference1.hyCodeServiceSoap)(this)).queryIfHasRegistered(inValue);
            return retVal.Body.queryIfHasRegisteredResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.ServiceReference1.activateVmcardQRcodeResponse test.ServiceReference1.hyCodeServiceSoap.activateVmcardQRcode(test.ServiceReference1.activateVmcardQRcodeRequest request) {
            return base.Channel.activateVmcardQRcode(request);
        }
        
        public string activateVmcardQRcode(string request) {
            test.ServiceReference1.activateVmcardQRcodeRequest inValue = new test.ServiceReference1.activateVmcardQRcodeRequest();
            inValue.Body = new test.ServiceReference1.activateVmcardQRcodeRequestBody();
            inValue.Body.request = request;
            test.ServiceReference1.activateVmcardQRcodeResponse retVal = ((test.ServiceReference1.hyCodeServiceSoap)(this)).activateVmcardQRcode(inValue);
            return retVal.Body.activateVmcardQRcodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.ServiceReference1.EncryptResponse test.ServiceReference1.hyCodeServiceSoap.Encrypt(test.ServiceReference1.EncryptRequest request) {
            return base.Channel.Encrypt(request);
        }
        
        public string Encrypt(string request) {
            test.ServiceReference1.EncryptRequest inValue = new test.ServiceReference1.EncryptRequest();
            inValue.Body = new test.ServiceReference1.EncryptRequestBody();
            inValue.Body.request = request;
            test.ServiceReference1.EncryptResponse retVal = ((test.ServiceReference1.hyCodeServiceSoap)(this)).Encrypt(inValue);
            return retVal.Body.EncryptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.ServiceReference1.DeEncryptResponse test.ServiceReference1.hyCodeServiceSoap.DeEncrypt(test.ServiceReference1.DeEncryptRequest request) {
            return base.Channel.DeEncrypt(request);
        }
        
        public string DeEncrypt(string request) {
            test.ServiceReference1.DeEncryptRequest inValue = new test.ServiceReference1.DeEncryptRequest();
            inValue.Body = new test.ServiceReference1.DeEncryptRequestBody();
            inValue.Body.request = request;
            test.ServiceReference1.DeEncryptResponse retVal = ((test.ServiceReference1.hyCodeServiceSoap)(this)).DeEncrypt(inValue);
            return retVal.Body.DeEncryptResult;
        }
    }
}
