//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.33440。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WebserviceCallEntranceImplServiceSoapBinding", Namespace="http://impl.webservice.iruitech.com/")]
public partial class WebserviceCallEntranceImplService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback CallFunOperationCompleted;
    
    /// <remarks/>
    public WebserviceCallEntranceImplService() {
        this.Url = "http://120.76.223.229:1080/sayifpf/webService/FdaWsOutsideEntrance";
    }
    
    /// <remarks/>
    public event CallFunCompletedEventHandler CallFunCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://interfaces.webservice.iruitech.com/", ResponseNamespace="http://interfaces.webservice.iruitech.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CallFun([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
        object[] results = this.Invoke("CallFun", new object[] {
                    arg0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCallFun(string arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CallFun", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndCallFun(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void CallFunAsync(string arg0) {
        this.CallFunAsync(arg0, null);
    }
    
    /// <remarks/>
    public void CallFunAsync(string arg0, object userState) {
        if ((this.CallFunOperationCompleted == null)) {
            this.CallFunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallFunOperationCompleted);
        }
        this.InvokeAsync("CallFun", new object[] {
                    arg0}, this.CallFunOperationCompleted, userState);
    }
    
    private void OnCallFunOperationCompleted(object arg) {
        if ((this.CallFunCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CallFunCompleted(this, new CallFunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void CallFunCompletedEventHandler(object sender, CallFunCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CallFunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CallFunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
