//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pe.test.ps.svc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ps.svc.PeInterface")]
    public interface PeInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcf/Verify", ReplyAction="http://tempuri.org/IWcf/VerifyResponse")]
        bool Verify();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PeInterface/CallFunc", ReplyAction="http://tempuri.org/PeInterface/CallFuncResponse")]
        string CallFunc(string request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PeInterfaceChannel : pe.test.ps.svc.PeInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PeInterfaceClient : System.ServiceModel.ClientBase<pe.test.ps.svc.PeInterface>, pe.test.ps.svc.PeInterface {
        
        public PeInterfaceClient() {
        }
        
        public PeInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Verify() {
            return base.Channel.Verify();
        }
        
        public string CallFunc(string request) {
            return base.Channel.CallFunc(request);
        }
    }
}
