regsvr32 /u Digital3DConstructor.ocx
regsvr32 /u DigitalDicom.ocx
regsvr32 /u DigitalDicomImageList.ocx
regsvr32 /u DigitalImageFuse.ocx
regsvr32 /u DigitalSerial.ocx
regsvr32 /u DigitDicomImage.ocx
regsvr32 /u SMScontrol.ocx
regsvr32 /u MSCOMM32.OCX
regsvr32 /u GetICUDataForm.ocx
regsvr32 /u EMR_GetICUDataForm.ocx